// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

@file:Suppress("NAME_SHADOWING")

package uniffi.slash_notes_core

// Common helper code.
//
// Ideally this would live in a separate .kt file where it can be unittested etc
// in isolation, and perhaps even published as a re-useable package.
//
// However, it's important that the details of how this helper code works (e.g. the
// way that different builtin types are passed across the FFI) exactly match what's
// expected by the Rust code on the other side of the interface. In practice right
// now that means coming from the exact some version of `uniffi` that was used to
// compile the Rust component. The easiest way to ensure this is to bundle the Kotlin
// helpers directly inline like we're doing here.

import com.sun.jna.Library
import com.sun.jna.IntegerType
import com.sun.jna.Native
import com.sun.jna.Pointer
import com.sun.jna.Structure
import com.sun.jna.Callback
import com.sun.jna.ptr.*
import java.nio.ByteBuffer
import java.nio.ByteOrder
import java.nio.CharBuffer
import java.nio.charset.CodingErrorAction
import java.util.concurrent.atomic.AtomicLong
import java.util.concurrent.ConcurrentHashMap

// This is a helper for safely working with byte buffers returned from the Rust code.
// A rust-owned buffer is represented by its capacity, its current length, and a
// pointer to the underlying data.

/**
 * @suppress
 */
@Structure.FieldOrder("capacity", "len", "data")
open class RustBuffer : Structure() {
    // Note: `capacity` and `len` are actually `ULong` values, but JVM only supports signed values.
    // When dealing with these fields, make sure to call `toULong()`.
    @JvmField var capacity: Long = 0
    @JvmField var len: Long = 0
    @JvmField var data: Pointer? = null

    class ByValue: RustBuffer(), Structure.ByValue
    class ByReference: RustBuffer(), Structure.ByReference

   internal fun setValue(other: RustBuffer) {
        capacity = other.capacity
        len = other.len
        data = other.data
    }

    companion object {
        internal fun alloc(size: ULong = 0UL) = uniffiRustCall() { status ->
            // Note: need to convert the size to a `Long` value to make this work with JVM.
            UniffiLib.INSTANCE.ffi_slash_notes_core_rustbuffer_alloc(size.toLong(), status)
        }.also {
            if(it.data == null) {
               throw RuntimeException("RustBuffer.alloc() returned null data pointer (size=${size})")
           }
        }

        internal fun create(capacity: ULong, len: ULong, data: Pointer?): RustBuffer.ByValue {
            var buf = RustBuffer.ByValue()
            buf.capacity = capacity.toLong()
            buf.len = len.toLong()
            buf.data = data
            return buf
        }

        internal fun free(buf: RustBuffer.ByValue) = uniffiRustCall() { status ->
            UniffiLib.INSTANCE.ffi_slash_notes_core_rustbuffer_free(buf, status)
        }
    }

    @Suppress("TooGenericExceptionThrown")
    fun asByteBuffer() =
        this.data?.getByteBuffer(0, this.len.toLong())?.also {
            it.order(ByteOrder.BIG_ENDIAN)
        }
}

/**
 * The equivalent of the `*mut RustBuffer` type.
 * Required for callbacks taking in an out pointer.
 *
 * Size is the sum of all values in the struct.
 *
 * @suppress
 */
class RustBufferByReference : ByReference(16) {
    /**
     * Set the pointed-to `RustBuffer` to the given value.
     */
    fun setValue(value: RustBuffer.ByValue) {
        // NOTE: The offsets are as they are in the C-like struct.
        val pointer = getPointer()
        pointer.setLong(0, value.capacity)
        pointer.setLong(8, value.len)
        pointer.setPointer(16, value.data)
    }

    /**
     * Get a `RustBuffer.ByValue` from this reference.
     */
    fun getValue(): RustBuffer.ByValue {
        val pointer = getPointer()
        val value = RustBuffer.ByValue()
        value.writeField("capacity", pointer.getLong(0))
        value.writeField("len", pointer.getLong(8))
        value.writeField("data", pointer.getLong(16))

        return value
    }
}

// This is a helper for safely passing byte references into the rust code.
// It's not actually used at the moment, because there aren't many things that you
// can take a direct pointer to in the JVM, and if we're going to copy something
// then we might as well copy it into a `RustBuffer`. But it's here for API
// completeness.

@Structure.FieldOrder("len", "data")
internal open class ForeignBytes : Structure() {
    @JvmField var len: Int = 0
    @JvmField var data: Pointer? = null

    class ByValue : ForeignBytes(), Structure.ByValue
}
/**
 * The FfiConverter interface handles converter types to and from the FFI
 *
 * All implementing objects should be public to support external types.  When a
 * type is external we need to import it's FfiConverter.
 *
 * @suppress
 */
public interface FfiConverter<KotlinType, FfiType> {
    // Convert an FFI type to a Kotlin type
    fun lift(value: FfiType): KotlinType

    // Convert an Kotlin type to an FFI type
    fun lower(value: KotlinType): FfiType

    // Read a Kotlin type from a `ByteBuffer`
    fun read(buf: ByteBuffer): KotlinType

    // Calculate bytes to allocate when creating a `RustBuffer`
    //
    // This must return at least as many bytes as the write() function will
    // write. It can return more bytes than needed, for example when writing
    // Strings we can't know the exact bytes needed until we the UTF-8
    // encoding, so we pessimistically allocate the largest size possible (3
    // bytes per codepoint).  Allocating extra bytes is not really a big deal
    // because the `RustBuffer` is short-lived.
    fun allocationSize(value: KotlinType): ULong

    // Write a Kotlin type to a `ByteBuffer`
    fun write(value: KotlinType, buf: ByteBuffer)

    // Lower a value into a `RustBuffer`
    //
    // This method lowers a value into a `RustBuffer` rather than the normal
    // FfiType.  It's used by the callback interface code.  Callback interface
    // returns are always serialized into a `RustBuffer` regardless of their
    // normal FFI type.
    fun lowerIntoRustBuffer(value: KotlinType): RustBuffer.ByValue {
        val rbuf = RustBuffer.alloc(allocationSize(value))
        try {
            val bbuf = rbuf.data!!.getByteBuffer(0, rbuf.capacity).also {
                it.order(ByteOrder.BIG_ENDIAN)
            }
            write(value, bbuf)
            rbuf.writeField("len", bbuf.position().toLong())
            return rbuf
        } catch (e: Throwable) {
            RustBuffer.free(rbuf)
            throw e
        }
    }

    // Lift a value from a `RustBuffer`.
    //
    // This here mostly because of the symmetry with `lowerIntoRustBuffer()`.
    // It's currently only used by the `FfiConverterRustBuffer` class below.
    fun liftFromRustBuffer(rbuf: RustBuffer.ByValue): KotlinType {
        val byteBuf = rbuf.asByteBuffer()!!
        try {
           val item = read(byteBuf)
           if (byteBuf.hasRemaining()) {
               throw RuntimeException("junk remaining in buffer after lifting, something is very wrong!!")
           }
           return item
        } finally {
            RustBuffer.free(rbuf)
        }
    }
}

/**
 * FfiConverter that uses `RustBuffer` as the FfiType
 *
 * @suppress
 */
public interface FfiConverterRustBuffer<KotlinType>: FfiConverter<KotlinType, RustBuffer.ByValue> {
    override fun lift(value: RustBuffer.ByValue) = liftFromRustBuffer(value)
    override fun lower(value: KotlinType) = lowerIntoRustBuffer(value)
}
// A handful of classes and functions to support the generated data structures.
// This would be a good candidate for isolating in its own ffi-support lib.

internal const val UNIFFI_CALL_SUCCESS = 0.toByte()
internal const val UNIFFI_CALL_ERROR = 1.toByte()
internal const val UNIFFI_CALL_UNEXPECTED_ERROR = 2.toByte()

@Structure.FieldOrder("code", "error_buf")
internal open class UniffiRustCallStatus : Structure() {
    @JvmField var code: Byte = 0
    @JvmField var error_buf: RustBuffer.ByValue = RustBuffer.ByValue()

    class ByValue: UniffiRustCallStatus(), Structure.ByValue

    fun isSuccess(): Boolean {
        return code == UNIFFI_CALL_SUCCESS
    }

    fun isError(): Boolean {
        return code == UNIFFI_CALL_ERROR
    }

    fun isPanic(): Boolean {
        return code == UNIFFI_CALL_UNEXPECTED_ERROR
    }

    companion object {
        fun create(code: Byte, errorBuf: RustBuffer.ByValue): UniffiRustCallStatus.ByValue {
            val callStatus = UniffiRustCallStatus.ByValue()
            callStatus.code = code
            callStatus.error_buf = errorBuf
            return callStatus
        }
    }
}

class InternalException(message: String) : kotlin.Exception(message)

/**
 * Each top-level error class has a companion object that can lift the error from the call status's rust buffer
 *
 * @suppress
 */
interface UniffiRustCallStatusErrorHandler<E> {
    fun lift(error_buf: RustBuffer.ByValue): E;
}

// Helpers for calling Rust
// In practice we usually need to be synchronized to call this safely, so it doesn't
// synchronize itself

// Call a rust function that returns a Result<>.  Pass in the Error class companion that corresponds to the Err
private inline fun <U, E: kotlin.Exception> uniffiRustCallWithError(errorHandler: UniffiRustCallStatusErrorHandler<E>, callback: (UniffiRustCallStatus) -> U): U {
    var status = UniffiRustCallStatus()
    val return_value = callback(status)
    uniffiCheckCallStatus(errorHandler, status)
    return return_value
}

// Check UniffiRustCallStatus and throw an error if the call wasn't successful
private fun<E: kotlin.Exception> uniffiCheckCallStatus(errorHandler: UniffiRustCallStatusErrorHandler<E>, status: UniffiRustCallStatus) {
    if (status.isSuccess()) {
        return
    } else if (status.isError()) {
        throw errorHandler.lift(status.error_buf)
    } else if (status.isPanic()) {
        // when the rust code sees a panic, it tries to construct a rustbuffer
        // with the message.  but if that code panics, then it just sends back
        // an empty buffer.
        if (status.error_buf.len > 0) {
            throw InternalException(FfiConverterString.lift(status.error_buf))
        } else {
            throw InternalException("Rust panic")
        }
    } else {
        throw InternalException("Unknown rust call status: $status.code")
    }
}

/**
 * UniffiRustCallStatusErrorHandler implementation for times when we don't expect a CALL_ERROR
 *
 * @suppress
 */
object UniffiNullRustCallStatusErrorHandler: UniffiRustCallStatusErrorHandler<InternalException> {
    override fun lift(error_buf: RustBuffer.ByValue): InternalException {
        RustBuffer.free(error_buf)
        return InternalException("Unexpected CALL_ERROR")
    }
}

// Call a rust function that returns a plain value
private inline fun <U> uniffiRustCall(callback: (UniffiRustCallStatus) -> U): U {
    return uniffiRustCallWithError(UniffiNullRustCallStatusErrorHandler, callback)
}

internal inline fun<T> uniffiTraitInterfaceCall(
    callStatus: UniffiRustCallStatus,
    makeCall: () -> T,
    writeReturn: (T) -> Unit,
) {
    try {
        writeReturn(makeCall())
    } catch(e: kotlin.Exception) {
        callStatus.code = UNIFFI_CALL_UNEXPECTED_ERROR
        callStatus.error_buf = FfiConverterString.lower(e.toString())
    }
}

internal inline fun<T, reified E: Throwable> uniffiTraitInterfaceCallWithError(
    callStatus: UniffiRustCallStatus,
    makeCall: () -> T,
    writeReturn: (T) -> Unit,
    lowerError: (E) -> RustBuffer.ByValue
) {
    try {
        writeReturn(makeCall())
    } catch(e: kotlin.Exception) {
        if (e is E) {
            callStatus.code = UNIFFI_CALL_ERROR
            callStatus.error_buf = lowerError(e)
        } else {
            callStatus.code = UNIFFI_CALL_UNEXPECTED_ERROR
            callStatus.error_buf = FfiConverterString.lower(e.toString())
        }
    }
}
// Map handles to objects
//
// This is used pass an opaque 64-bit handle representing a foreign object to the Rust code.
internal class UniffiHandleMap<T: Any> {
    private val map = ConcurrentHashMap<Long, T>()
    private val counter = java.util.concurrent.atomic.AtomicLong(0)

    val size: Int
        get() = map.size

    // Insert a new object into the handle map and get a handle for it
    fun insert(obj: T): Long {
        val handle = counter.getAndAdd(1)
        map.put(handle, obj)
        return handle
    }

    // Get an object from the handle map
    fun get(handle: Long): T {
        return map.get(handle) ?: throw InternalException("UniffiHandleMap.get: Invalid handle")
    }

    // Remove an entry from the handlemap and get the Kotlin object back
    fun remove(handle: Long): T {
        return map.remove(handle) ?: throw InternalException("UniffiHandleMap: Invalid handle")
    }
}

// Contains loading, initialization code,
// and the FFI Function declarations in a com.sun.jna.Library.
@Synchronized
private fun findLibraryName(componentName: String): String {
    val libOverride = System.getProperty("uniffi.component.$componentName.libraryOverride")
    if (libOverride != null) {
        return libOverride
    }
    return "slash_notes_core"
}

private inline fun <reified Lib : Library> loadIndirect(
    componentName: String
): Lib {
    return Native.load<Lib>(findLibraryName(componentName), Lib::class.java)
}

// Define FFI callback types
internal interface UniffiRustFutureContinuationCallback : com.sun.jna.Callback {
    fun callback(`data`: Long,`pollResult`: Byte,)
}
internal interface UniffiForeignFutureFree : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
}
internal interface UniffiCallbackInterfaceFree : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
}
@Structure.FieldOrder("handle", "free")
internal open class UniffiForeignFuture(
    @JvmField internal var `handle`: Long = 0.toLong(),
    @JvmField internal var `free`: UniffiForeignFutureFree? = null,
) : Structure() {
    class UniffiByValue(
        `handle`: Long = 0.toLong(),
        `free`: UniffiForeignFutureFree? = null,
    ): UniffiForeignFuture(`handle`,`free`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFuture) {
        `handle` = other.`handle`
        `free` = other.`free`
    }

}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructU8(
    @JvmField internal var `returnValue`: Byte = 0.toByte(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Byte = 0.toByte(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructU8(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructU8) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU8 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructU8.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructI8(
    @JvmField internal var `returnValue`: Byte = 0.toByte(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Byte = 0.toByte(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructI8(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructI8) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI8 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructI8.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructU16(
    @JvmField internal var `returnValue`: Short = 0.toShort(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Short = 0.toShort(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructU16(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructU16) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU16 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructU16.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructI16(
    @JvmField internal var `returnValue`: Short = 0.toShort(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Short = 0.toShort(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructI16(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructI16) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI16 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructI16.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructU32(
    @JvmField internal var `returnValue`: Int = 0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Int = 0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructU32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructU32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructU32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructI32(
    @JvmField internal var `returnValue`: Int = 0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Int = 0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructI32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructI32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructI32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructU64(
    @JvmField internal var `returnValue`: Long = 0.toLong(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Long = 0.toLong(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructU64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructU64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructU64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructI64(
    @JvmField internal var `returnValue`: Long = 0.toLong(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Long = 0.toLong(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructI64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructI64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructI64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructF32(
    @JvmField internal var `returnValue`: Float = 0.0f,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Float = 0.0f,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructF32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructF32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteF32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructF32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructF64(
    @JvmField internal var `returnValue`: Double = 0.0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Double = 0.0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructF64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructF64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteF64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructF64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructPointer(
    @JvmField internal var `returnValue`: Pointer = Pointer.NULL,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Pointer = Pointer.NULL,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructPointer(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructPointer) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompletePointer : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructPointer.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructRustBuffer(
    @JvmField internal var `returnValue`: RustBuffer.ByValue = RustBuffer.ByValue(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: RustBuffer.ByValue = RustBuffer.ByValue(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructRustBuffer(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructRustBuffer) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteRustBuffer : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructRustBuffer.UniffiByValue,)
}
@Structure.FieldOrder("callStatus")
internal open class UniffiForeignFutureStructVoid(
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructVoid(`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructVoid) {
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteVoid : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructVoid.UniffiByValue,)
}










































































































// A JNA Library to expose the extern-C FFI definitions.
// This is an implementation detail which will be called internally by the public API.

internal interface UniffiLib : Library {
    companion object {
        internal val INSTANCE: UniffiLib by lazy {
            loadIndirect<UniffiLib>(componentName = "slash_notes_core")
            .also { lib: UniffiLib ->
                uniffiCheckContractApiVersion(lib)
                uniffiCheckApiChecksums(lib)
                }
        }
        
    }

    fun uniffi_slash_notes_core_fn_func_check_git_connection(`repoPath`: RustBuffer.ByValue,`token`: RustBuffer.ByValue,`remoteUrl`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_slash_notes_core_fn_func_create_folder(`rootPath`: RustBuffer.ByValue,`relativeDir`: RustBuffer.ByValue,`folderName`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Byte
    fun uniffi_slash_notes_core_fn_func_create_note(`dirPath`: RustBuffer.ByValue,`titleOrTemplate`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_slash_notes_core_fn_func_delete_item(`rootPath`: RustBuffer.ByValue,`relativePath`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Byte
    fun uniffi_slash_notes_core_fn_func_delete_note(`dirPath`: RustBuffer.ByValue,`filename`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Byte
    fun uniffi_slash_notes_core_fn_func_duplicate_note(`dirPath`: RustBuffer.ByValue,`filename`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_slash_notes_core_fn_func_empty_trash(`rootPath`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    fun uniffi_slash_notes_core_fn_func_get_cached_note_headers(`rootPath`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_slash_notes_core_fn_func_get_core_version(uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_slash_notes_core_fn_func_init_git_repository(`repoPath`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    fun uniffi_slash_notes_core_fn_func_list_folder_contents(`rootPath`: RustBuffer.ByValue,`relativeDir`: RustBuffer.ByValue,`showAllFiles`: Byte,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_slash_notes_core_fn_func_list_notes(`dirPath`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_slash_notes_core_fn_func_list_trash_contents(`rootPath`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_slash_notes_core_fn_func_load_vault_index(`rootPath`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_slash_notes_core_fn_func_move_item(`rootPath`: RustBuffer.ByValue,`sourceRelativePath`: RustBuffer.ByValue,`destRelativeDir`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    fun uniffi_slash_notes_core_fn_func_move_to_trash(`rootPath`: RustBuffer.ByValue,`relativePath`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    fun uniffi_slash_notes_core_fn_func_parse_markdown_tokens(`content`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_slash_notes_core_fn_func_preview_note_name(`template`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_slash_notes_core_fn_func_read_note(`dirPath`: RustBuffer.ByValue,`filename`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_slash_notes_core_fn_func_rename_item(`rootPath`: RustBuffer.ByValue,`oldRelativePath`: RustBuffer.ByValue,`newName`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Byte
    fun uniffi_slash_notes_core_fn_func_restore_from_trash(`rootPath`: RustBuffer.ByValue,`relativePath`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    fun uniffi_slash_notes_core_fn_func_save_note(`dirPath`: RustBuffer.ByValue,`filename`: RustBuffer.ByValue,`content`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Byte
    fun uniffi_slash_notes_core_fn_func_search_notes(`dirPath`: RustBuffer.ByValue,`query`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_slash_notes_core_fn_func_sync_git_repository(`repoPath`: RustBuffer.ByValue,`token`: RustBuffer.ByValue,`remoteUrl`: RustBuffer.ByValue,`branch`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun ffi_slash_notes_core_rustbuffer_alloc(`size`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun ffi_slash_notes_core_rustbuffer_from_bytes(`bytes`: ForeignBytes.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun ffi_slash_notes_core_rustbuffer_free(`buf`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    fun ffi_slash_notes_core_rustbuffer_reserve(`buf`: RustBuffer.ByValue,`additional`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun ffi_slash_notes_core_rust_future_poll_u8(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_slash_notes_core_rust_future_cancel_u8(`handle`: Long,
    ): Unit
    fun ffi_slash_notes_core_rust_future_free_u8(`handle`: Long,
    ): Unit
    fun ffi_slash_notes_core_rust_future_complete_u8(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Byte
    fun ffi_slash_notes_core_rust_future_poll_i8(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_slash_notes_core_rust_future_cancel_i8(`handle`: Long,
    ): Unit
    fun ffi_slash_notes_core_rust_future_free_i8(`handle`: Long,
    ): Unit
    fun ffi_slash_notes_core_rust_future_complete_i8(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Byte
    fun ffi_slash_notes_core_rust_future_poll_u16(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_slash_notes_core_rust_future_cancel_u16(`handle`: Long,
    ): Unit
    fun ffi_slash_notes_core_rust_future_free_u16(`handle`: Long,
    ): Unit
    fun ffi_slash_notes_core_rust_future_complete_u16(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Short
    fun ffi_slash_notes_core_rust_future_poll_i16(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_slash_notes_core_rust_future_cancel_i16(`handle`: Long,
    ): Unit
    fun ffi_slash_notes_core_rust_future_free_i16(`handle`: Long,
    ): Unit
    fun ffi_slash_notes_core_rust_future_complete_i16(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Short
    fun ffi_slash_notes_core_rust_future_poll_u32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_slash_notes_core_rust_future_cancel_u32(`handle`: Long,
    ): Unit
    fun ffi_slash_notes_core_rust_future_free_u32(`handle`: Long,
    ): Unit
    fun ffi_slash_notes_core_rust_future_complete_u32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Int
    fun ffi_slash_notes_core_rust_future_poll_i32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_slash_notes_core_rust_future_cancel_i32(`handle`: Long,
    ): Unit
    fun ffi_slash_notes_core_rust_future_free_i32(`handle`: Long,
    ): Unit
    fun ffi_slash_notes_core_rust_future_complete_i32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Int
    fun ffi_slash_notes_core_rust_future_poll_u64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_slash_notes_core_rust_future_cancel_u64(`handle`: Long,
    ): Unit
    fun ffi_slash_notes_core_rust_future_free_u64(`handle`: Long,
    ): Unit
    fun ffi_slash_notes_core_rust_future_complete_u64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Long
    fun ffi_slash_notes_core_rust_future_poll_i64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_slash_notes_core_rust_future_cancel_i64(`handle`: Long,
    ): Unit
    fun ffi_slash_notes_core_rust_future_free_i64(`handle`: Long,
    ): Unit
    fun ffi_slash_notes_core_rust_future_complete_i64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Long
    fun ffi_slash_notes_core_rust_future_poll_f32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_slash_notes_core_rust_future_cancel_f32(`handle`: Long,
    ): Unit
    fun ffi_slash_notes_core_rust_future_free_f32(`handle`: Long,
    ): Unit
    fun ffi_slash_notes_core_rust_future_complete_f32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Float
    fun ffi_slash_notes_core_rust_future_poll_f64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_slash_notes_core_rust_future_cancel_f64(`handle`: Long,
    ): Unit
    fun ffi_slash_notes_core_rust_future_free_f64(`handle`: Long,
    ): Unit
    fun ffi_slash_notes_core_rust_future_complete_f64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Double
    fun ffi_slash_notes_core_rust_future_poll_pointer(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_slash_notes_core_rust_future_cancel_pointer(`handle`: Long,
    ): Unit
    fun ffi_slash_notes_core_rust_future_free_pointer(`handle`: Long,
    ): Unit
    fun ffi_slash_notes_core_rust_future_complete_pointer(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Pointer
    fun ffi_slash_notes_core_rust_future_poll_rust_buffer(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_slash_notes_core_rust_future_cancel_rust_buffer(`handle`: Long,
    ): Unit
    fun ffi_slash_notes_core_rust_future_free_rust_buffer(`handle`: Long,
    ): Unit
    fun ffi_slash_notes_core_rust_future_complete_rust_buffer(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun ffi_slash_notes_core_rust_future_poll_void(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_slash_notes_core_rust_future_cancel_void(`handle`: Long,
    ): Unit
    fun ffi_slash_notes_core_rust_future_free_void(`handle`: Long,
    ): Unit
    fun ffi_slash_notes_core_rust_future_complete_void(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    fun uniffi_slash_notes_core_checksum_func_check_git_connection(
    ): Short
    fun uniffi_slash_notes_core_checksum_func_create_folder(
    ): Short
    fun uniffi_slash_notes_core_checksum_func_create_note(
    ): Short
    fun uniffi_slash_notes_core_checksum_func_delete_item(
    ): Short
    fun uniffi_slash_notes_core_checksum_func_delete_note(
    ): Short
    fun uniffi_slash_notes_core_checksum_func_duplicate_note(
    ): Short
    fun uniffi_slash_notes_core_checksum_func_empty_trash(
    ): Short
    fun uniffi_slash_notes_core_checksum_func_get_cached_note_headers(
    ): Short
    fun uniffi_slash_notes_core_checksum_func_get_core_version(
    ): Short
    fun uniffi_slash_notes_core_checksum_func_init_git_repository(
    ): Short
    fun uniffi_slash_notes_core_checksum_func_list_folder_contents(
    ): Short
    fun uniffi_slash_notes_core_checksum_func_list_notes(
    ): Short
    fun uniffi_slash_notes_core_checksum_func_list_trash_contents(
    ): Short
    fun uniffi_slash_notes_core_checksum_func_load_vault_index(
    ): Short
    fun uniffi_slash_notes_core_checksum_func_move_item(
    ): Short
    fun uniffi_slash_notes_core_checksum_func_move_to_trash(
    ): Short
    fun uniffi_slash_notes_core_checksum_func_parse_markdown_tokens(
    ): Short
    fun uniffi_slash_notes_core_checksum_func_preview_note_name(
    ): Short
    fun uniffi_slash_notes_core_checksum_func_read_note(
    ): Short
    fun uniffi_slash_notes_core_checksum_func_rename_item(
    ): Short
    fun uniffi_slash_notes_core_checksum_func_restore_from_trash(
    ): Short
    fun uniffi_slash_notes_core_checksum_func_save_note(
    ): Short
    fun uniffi_slash_notes_core_checksum_func_search_notes(
    ): Short
    fun uniffi_slash_notes_core_checksum_func_sync_git_repository(
    ): Short
    fun ffi_slash_notes_core_uniffi_contract_version(
    ): Int
    
}

private fun uniffiCheckContractApiVersion(lib: UniffiLib) {
    // Get the bindings contract version from our ComponentInterface
    val bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    val scaffolding_contract_version = lib.ffi_slash_notes_core_uniffi_contract_version()
    if (bindings_contract_version != scaffolding_contract_version) {
        throw RuntimeException("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    }
}

@Suppress("UNUSED_PARAMETER")
private fun uniffiCheckApiChecksums(lib: UniffiLib) {
    if (lib.uniffi_slash_notes_core_checksum_func_check_git_connection() != 22817.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_slash_notes_core_checksum_func_create_folder() != 16118.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_slash_notes_core_checksum_func_create_note() != 28389.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_slash_notes_core_checksum_func_delete_item() != 18085.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_slash_notes_core_checksum_func_delete_note() != 12135.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_slash_notes_core_checksum_func_duplicate_note() != 48001.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_slash_notes_core_checksum_func_empty_trash() != 36288.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_slash_notes_core_checksum_func_get_cached_note_headers() != 53311.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_slash_notes_core_checksum_func_get_core_version() != 51747.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_slash_notes_core_checksum_func_init_git_repository() != 14751.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_slash_notes_core_checksum_func_list_folder_contents() != 13092.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_slash_notes_core_checksum_func_list_notes() != 30068.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_slash_notes_core_checksum_func_list_trash_contents() != 25440.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_slash_notes_core_checksum_func_load_vault_index() != 40139.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_slash_notes_core_checksum_func_move_item() != 45230.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_slash_notes_core_checksum_func_move_to_trash() != 27030.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_slash_notes_core_checksum_func_parse_markdown_tokens() != 26817.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_slash_notes_core_checksum_func_preview_note_name() != 53028.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_slash_notes_core_checksum_func_read_note() != 40628.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_slash_notes_core_checksum_func_rename_item() != 65133.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_slash_notes_core_checksum_func_restore_from_trash() != 31245.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_slash_notes_core_checksum_func_save_note() != 48316.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_slash_notes_core_checksum_func_search_notes() != 65492.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_slash_notes_core_checksum_func_sync_git_repository() != 32755.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// Async support

// Public interface members begin here.


// Interface implemented by anything that can contain an object reference.
//
// Such types expose a `destroy()` method that must be called to cleanly
// dispose of the contained objects. Failure to call this method may result
// in memory leaks.
//
// The easiest way to ensure this method is called is to use the `.use`
// helper method to execute a block and destroy the object at the end.
interface Disposable {
    fun destroy()
    companion object {
        fun destroy(vararg args: Any?) {
            args.filterIsInstance<Disposable>()
                .forEach(Disposable::destroy)
        }
    }
}

/**
 * @suppress
 */
inline fun <T : Disposable?, R> T.use(block: (T) -> R) =
    try {
        block(this)
    } finally {
        try {
            // N.B. our implementation is on the nullable type `Disposable?`.
            this?.destroy()
        } catch (e: Throwable) {
            // swallow
        }
    }

/** 
 * Used to instantiate an interface without an actual pointer, for fakes in tests, mostly.
 *
 * @suppress
 * */
object NoPointer

/**
 * @suppress
 */
public object FfiConverterUByte: FfiConverter<UByte, Byte> {
    override fun lift(value: Byte): UByte {
        return value.toUByte()
    }

    override fun read(buf: ByteBuffer): UByte {
        return lift(buf.get())
    }

    override fun lower(value: UByte): Byte {
        return value.toByte()
    }

    override fun allocationSize(value: UByte) = 1UL

    override fun write(value: UByte, buf: ByteBuffer) {
        buf.put(value.toByte())
    }
}

/**
 * @suppress
 */
public object FfiConverterUInt: FfiConverter<UInt, Int> {
    override fun lift(value: Int): UInt {
        return value.toUInt()
    }

    override fun read(buf: ByteBuffer): UInt {
        return lift(buf.getInt())
    }

    override fun lower(value: UInt): Int {
        return value.toInt()
    }

    override fun allocationSize(value: UInt) = 4UL

    override fun write(value: UInt, buf: ByteBuffer) {
        buf.putInt(value.toInt())
    }
}

/**
 * @suppress
 */
public object FfiConverterLong: FfiConverter<Long, Long> {
    override fun lift(value: Long): Long {
        return value
    }

    override fun read(buf: ByteBuffer): Long {
        return buf.getLong()
    }

    override fun lower(value: Long): Long {
        return value
    }

    override fun allocationSize(value: Long) = 8UL

    override fun write(value: Long, buf: ByteBuffer) {
        buf.putLong(value)
    }
}

/**
 * @suppress
 */
public object FfiConverterBoolean: FfiConverter<Boolean, Byte> {
    override fun lift(value: Byte): Boolean {
        return value.toInt() != 0
    }

    override fun read(buf: ByteBuffer): Boolean {
        return lift(buf.get())
    }

    override fun lower(value: Boolean): Byte {
        return if (value) 1.toByte() else 0.toByte()
    }

    override fun allocationSize(value: Boolean) = 1UL

    override fun write(value: Boolean, buf: ByteBuffer) {
        buf.put(lower(value))
    }
}

/**
 * @suppress
 */
public object FfiConverterString: FfiConverter<String, RustBuffer.ByValue> {
    // Note: we don't inherit from FfiConverterRustBuffer, because we use a
    // special encoding when lowering/lifting.  We can use `RustBuffer.len` to
    // store our length and avoid writing it out to the buffer.
    override fun lift(value: RustBuffer.ByValue): String {
        try {
            val byteArr = ByteArray(value.len.toInt())
            value.asByteBuffer()!!.get(byteArr)
            return byteArr.toString(Charsets.UTF_8)
        } finally {
            RustBuffer.free(value)
        }
    }

    override fun read(buf: ByteBuffer): String {
        val len = buf.getInt()
        val byteArr = ByteArray(len)
        buf.get(byteArr)
        return byteArr.toString(Charsets.UTF_8)
    }

    fun toUtf8(value: String): ByteBuffer {
        // Make sure we don't have invalid UTF-16, check for lone surrogates.
        return Charsets.UTF_8.newEncoder().run {
            onMalformedInput(CodingErrorAction.REPORT)
            encode(CharBuffer.wrap(value))
        }
    }

    override fun lower(value: String): RustBuffer.ByValue {
        val byteBuf = toUtf8(value)
        // Ideally we'd pass these bytes to `ffi_bytebuffer_from_bytes`, but doing so would require us
        // to copy them into a JNA `Memory`. So we might as well directly copy them into a `RustBuffer`.
        val rbuf = RustBuffer.alloc(byteBuf.limit().toULong())
        rbuf.asByteBuffer()!!.put(byteBuf)
        return rbuf
    }

    // We aren't sure exactly how many bytes our string will be once it's UTF-8
    // encoded.  Allocate 3 bytes per UTF-16 code unit which will always be
    // enough.
    override fun allocationSize(value: String): ULong {
        val sizeForLength = 4UL
        val sizeForString = value.length.toULong() * 3UL
        return sizeForLength + sizeForString
    }

    override fun write(value: String, buf: ByteBuffer) {
        val byteBuf = toUtf8(value)
        buf.putInt(byteBuf.limit())
        buf.put(byteBuf)
    }
}



/**
 * Per-note metadata cached in memory so UI scrolling never hits the disk.
 */
data class CachedNoteHeader (
    var `title`: kotlin.String, 
    var `relativePath`: kotlin.String, 
    var `lastModifiedUnix`: kotlin.Long
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeCachedNoteHeader: FfiConverterRustBuffer<CachedNoteHeader> {
    override fun read(buf: ByteBuffer): CachedNoteHeader {
        return CachedNoteHeader(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterLong.read(buf),
        )
    }

    override fun allocationSize(value: CachedNoteHeader) = (
            FfiConverterString.allocationSize(value.`title`) +
            FfiConverterString.allocationSize(value.`relativePath`) +
            FfiConverterLong.allocationSize(value.`lastModifiedUnix`)
    )

    override fun write(value: CachedNoteHeader, buf: ByteBuffer) {
            FfiConverterString.write(value.`title`, buf)
            FfiConverterString.write(value.`relativePath`, buf)
            FfiConverterLong.write(value.`lastModifiedUnix`, buf)
    }
}



/**
 * Directory or file entry returned by folder listing APIs.
 */
data class FolderItem (
    var `name`: kotlin.String, 
    var `relativePath`: kotlin.String, 
    var `isDir`: kotlin.Boolean
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeFolderItem: FfiConverterRustBuffer<FolderItem> {
    override fun read(buf: ByteBuffer): FolderItem {
        return FolderItem(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterBoolean.read(buf),
        )
    }

    override fun allocationSize(value: FolderItem) = (
            FfiConverterString.allocationSize(value.`name`) +
            FfiConverterString.allocationSize(value.`relativePath`) +
            FfiConverterBoolean.allocationSize(value.`isDir`)
    )

    override fun write(value: FolderItem, buf: ByteBuffer) {
            FfiConverterString.write(value.`name`, buf)
            FfiConverterString.write(value.`relativePath`, buf)
            FfiConverterBoolean.write(value.`isDir`, buf)
    }
}



data class MarkdownSpan (
    var `start`: kotlin.UInt, 
    var `end`: kotlin.UInt, 
    var `kind`: kotlin.UByte
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeMarkdownSpan: FfiConverterRustBuffer<MarkdownSpan> {
    override fun read(buf: ByteBuffer): MarkdownSpan {
        return MarkdownSpan(
            FfiConverterUInt.read(buf),
            FfiConverterUInt.read(buf),
            FfiConverterUByte.read(buf),
        )
    }

    override fun allocationSize(value: MarkdownSpan) = (
            FfiConverterUInt.allocationSize(value.`start`) +
            FfiConverterUInt.allocationSize(value.`end`) +
            FfiConverterUByte.allocationSize(value.`kind`)
    )

    override fun write(value: MarkdownSpan, buf: ByteBuffer) {
            FfiConverterUInt.write(value.`start`, buf)
            FfiConverterUInt.write(value.`end`, buf)
            FfiConverterUByte.write(value.`kind`, buf)
    }
}



data class NoteHeader (
    var `id`: kotlin.String, 
    var `title`: kotlin.String
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeNoteHeader: FfiConverterRustBuffer<NoteHeader> {
    override fun read(buf: ByteBuffer): NoteHeader {
        return NoteHeader(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
        )
    }

    override fun allocationSize(value: NoteHeader) = (
            FfiConverterString.allocationSize(value.`id`) +
            FfiConverterString.allocationSize(value.`title`)
    )

    override fun write(value: NoteHeader, buf: ByteBuffer) {
            FfiConverterString.write(value.`id`, buf)
            FfiConverterString.write(value.`title`, buf)
    }
}





sealed class CoreException: kotlin.Exception() {
    
    class SyncException(
        
        val `msg`: kotlin.String
        ) : CoreException() {
        override val message
            get() = "msg=${ `msg` }"
    }
    
    class VaultException(
        
        val `msg`: kotlin.String
        ) : CoreException() {
        override val message
            get() = "msg=${ `msg` }"
    }
    

    companion object ErrorHandler : UniffiRustCallStatusErrorHandler<CoreException> {
        override fun lift(error_buf: RustBuffer.ByValue): CoreException = FfiConverterTypeCoreError.lift(error_buf)
    }

    
}

/**
 * @suppress
 */
public object FfiConverterTypeCoreError : FfiConverterRustBuffer<CoreException> {
    override fun read(buf: ByteBuffer): CoreException {
        

        return when(buf.getInt()) {
            1 -> CoreException.SyncException(
                FfiConverterString.read(buf),
                )
            2 -> CoreException.VaultException(
                FfiConverterString.read(buf),
                )
            else -> throw RuntimeException("invalid error enum value, something is very wrong!!")
        }
    }

    override fun allocationSize(value: CoreException): ULong {
        return when(value) {
            is CoreException.SyncException -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
                + FfiConverterString.allocationSize(value.`msg`)
            )
            is CoreException.VaultException -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
                + FfiConverterString.allocationSize(value.`msg`)
            )
        }
    }

    override fun write(value: CoreException, buf: ByteBuffer) {
        when(value) {
            is CoreException.SyncException -> {
                buf.putInt(1)
                FfiConverterString.write(value.`msg`, buf)
                Unit
            }
            is CoreException.VaultException -> {
                buf.putInt(2)
                FfiConverterString.write(value.`msg`, buf)
                Unit
            }
        }.let { /* this makes the `when` an expression, which ensures it is exhaustive */ }
    }

}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeCachedNoteHeader: FfiConverterRustBuffer<List<CachedNoteHeader>> {
    override fun read(buf: ByteBuffer): List<CachedNoteHeader> {
        val len = buf.getInt()
        return List<CachedNoteHeader>(len) {
            FfiConverterTypeCachedNoteHeader.read(buf)
        }
    }

    override fun allocationSize(value: List<CachedNoteHeader>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeCachedNoteHeader.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<CachedNoteHeader>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeCachedNoteHeader.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeFolderItem: FfiConverterRustBuffer<List<FolderItem>> {
    override fun read(buf: ByteBuffer): List<FolderItem> {
        val len = buf.getInt()
        return List<FolderItem>(len) {
            FfiConverterTypeFolderItem.read(buf)
        }
    }

    override fun allocationSize(value: List<FolderItem>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeFolderItem.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<FolderItem>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeFolderItem.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeMarkdownSpan: FfiConverterRustBuffer<List<MarkdownSpan>> {
    override fun read(buf: ByteBuffer): List<MarkdownSpan> {
        val len = buf.getInt()
        return List<MarkdownSpan>(len) {
            FfiConverterTypeMarkdownSpan.read(buf)
        }
    }

    override fun allocationSize(value: List<MarkdownSpan>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeMarkdownSpan.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<MarkdownSpan>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeMarkdownSpan.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeNoteHeader: FfiConverterRustBuffer<List<NoteHeader>> {
    override fun read(buf: ByteBuffer): List<NoteHeader> {
        val len = buf.getInt()
        return List<NoteHeader>(len) {
            FfiConverterTypeNoteHeader.read(buf)
        }
    }

    override fun allocationSize(value: List<NoteHeader>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeNoteHeader.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<NoteHeader>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeNoteHeader.write(it, buf)
        }
    }
}
        /**
         * Verify connectivity to the configured git remote without mutating anything.
         *
         * This performs a lightweight `git ls-remote` (or, if unavailable, a
         * credentials + host reachability probe) and reports whether the repo and
         * remote are valid. Intended for the "Test Connection" button in the
         * Git & Sync settings tab.
         */
    @Throws(CoreException::class) fun `checkGitConnection`(`repoPath`: kotlin.String, `token`: kotlin.String, `remoteUrl`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(CoreException) { _status ->
    UniffiLib.INSTANCE.uniffi_slash_notes_core_fn_func_check_git_connection(
        FfiConverterString.lower(`repoPath`),FfiConverterString.lower(`token`),FfiConverterString.lower(`remoteUrl`),_status)
}
    )
    }
    
 fun `createFolder`(`rootPath`: kotlin.String, `relativeDir`: kotlin.String, `folderName`: kotlin.String): kotlin.Boolean {
            return FfiConverterBoolean.lift(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_slash_notes_core_fn_func_create_folder(
        FfiConverterString.lower(`rootPath`),FfiConverterString.lower(`relativeDir`),FfiConverterString.lower(`folderName`),_status)
}
    )
    }
    
 fun `createNote`(`dirPath`: kotlin.String, `titleOrTemplate`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_slash_notes_core_fn_func_create_note(
        FfiConverterString.lower(`dirPath`),FfiConverterString.lower(`titleOrTemplate`),_status)
}
    )
    }
    
 fun `deleteItem`(`rootPath`: kotlin.String, `relativePath`: kotlin.String): kotlin.Boolean {
            return FfiConverterBoolean.lift(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_slash_notes_core_fn_func_delete_item(
        FfiConverterString.lower(`rootPath`),FfiConverterString.lower(`relativePath`),_status)
}
    )
    }
    
 fun `deleteNote`(`dirPath`: kotlin.String, `filename`: kotlin.String): kotlin.Boolean {
            return FfiConverterBoolean.lift(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_slash_notes_core_fn_func_delete_note(
        FfiConverterString.lower(`dirPath`),FfiConverterString.lower(`filename`),_status)
}
    )
    }
    
 fun `duplicateNote`(`dirPath`: kotlin.String, `filename`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_slash_notes_core_fn_func_duplicate_note(
        FfiConverterString.lower(`dirPath`),FfiConverterString.lower(`filename`),_status)
}
    )
    }
    

        /**
         * Permanently delete everything inside the native `.trash/` directory.
         */
    @Throws(CoreException::class) fun `emptyTrash`(`rootPath`: kotlin.String)
        = 
    uniffiRustCallWithError(CoreException) { _status ->
    UniffiLib.INSTANCE.uniffi_slash_notes_core_fn_func_empty_trash(
        FfiConverterString.lower(`rootPath`),_status)
}
    
    

        /**
         * Return note metadata from the in-memory index (indexing on first access).
         */ fun `getCachedNoteHeaders`(`rootPath`: kotlin.String): List<CachedNoteHeader> {
            return FfiConverterSequenceTypeCachedNoteHeader.lift(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_slash_notes_core_fn_func_get_cached_note_headers(
        FfiConverterString.lower(`rootPath`),_status)
}
    )
    }
    
 fun `getCoreVersion`(): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_slash_notes_core_fn_func_get_core_version(
        _status)
}
    )
    }
    

        /**
         * Initialize a git repository at the given POSIX directory path.
         *
         * This is the explicit init step that must be called with a physical path
         * (never a `content://` URI) before syncing. It is idempotent: if a valid
         * repository already exists, it succeeds without reinitializing.
         */
    @Throws(CoreException::class) fun `initGitRepository`(`repoPath`: kotlin.String)
        = 
    uniffiRustCallWithError(CoreException) { _status ->
    UniffiLib.INSTANCE.uniffi_slash_notes_core_fn_func_init_git_repository(
        FfiConverterString.lower(`repoPath`),_status)
}
    
    
 fun `listFolderContents`(`rootPath`: kotlin.String, `relativeDir`: kotlin.String, `showAllFiles`: kotlin.Boolean): List<FolderItem> {
            return FfiConverterSequenceTypeFolderItem.lift(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_slash_notes_core_fn_func_list_folder_contents(
        FfiConverterString.lower(`rootPath`),FfiConverterString.lower(`relativeDir`),FfiConverterBoolean.lower(`showAllFiles`),_status)
}
    )
    }
    
 fun `listNotes`(`dirPath`: kotlin.String): List<NoteHeader> {
            return FfiConverterSequenceTypeNoteHeader.lift(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_slash_notes_core_fn_func_list_notes(
        FfiConverterString.lower(`dirPath`),_status)
}
    )
    }
    

        /**
         * List the contents of the native `.trash/` directory.
         */ fun `listTrashContents`(`rootPath`: kotlin.String): List<FolderItem> {
            return FfiConverterSequenceTypeFolderItem.lift(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_slash_notes_core_fn_func_list_trash_contents(
        FfiConverterString.lower(`rootPath`),_status)
}
    )
    }
    

        /**
         * Load (or refresh) the in-memory vault index and return cached note metadata.
         */ fun `loadVaultIndex`(`rootPath`: kotlin.String): List<CachedNoteHeader> {
            return FfiConverterSequenceTypeCachedNoteHeader.lift(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_slash_notes_core_fn_func_load_vault_index(
        FfiConverterString.lower(`rootPath`),_status)
}
    )
    }
    

        /**
         * Move an item (file or folder) from one directory to another.
         */
    @Throws(CoreException::class) fun `moveItem`(`rootPath`: kotlin.String, `sourceRelativePath`: kotlin.String, `destRelativeDir`: kotlin.String)
        = 
    uniffiRustCallWithError(CoreException) { _status ->
    UniffiLib.INSTANCE.uniffi_slash_notes_core_fn_func_move_item(
        FfiConverterString.lower(`rootPath`),FfiConverterString.lower(`sourceRelativePath`),FfiConverterString.lower(`destRelativeDir`),_status)
}
    
    

        /**
         * Move an item into the native `.trash/` directory.
         */
    @Throws(CoreException::class) fun `moveToTrash`(`rootPath`: kotlin.String, `relativePath`: kotlin.String)
        = 
    uniffiRustCallWithError(CoreException) { _status ->
    UniffiLib.INSTANCE.uniffi_slash_notes_core_fn_func_move_to_trash(
        FfiConverterString.lower(`rootPath`),FfiConverterString.lower(`relativePath`),_status)
}
    
    
 fun `parseMarkdownTokens`(`content`: kotlin.String): List<MarkdownSpan> {
            return FfiConverterSequenceTypeMarkdownSpan.lift(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_slash_notes_core_fn_func_parse_markdown_tokens(
        FfiConverterString.lower(`content`),_status)
}
    )
    }
    

        /**
         * Expands note name template tags using local time
         */ fun `previewNoteName`(`template`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_slash_notes_core_fn_func_preview_note_name(
        FfiConverterString.lower(`template`),_status)
}
    )
    }
    
 fun `readNote`(`dirPath`: kotlin.String, `filename`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_slash_notes_core_fn_func_read_note(
        FfiConverterString.lower(`dirPath`),FfiConverterString.lower(`filename`),_status)
}
    )
    }
    
 fun `renameItem`(`rootPath`: kotlin.String, `oldRelativePath`: kotlin.String, `newName`: kotlin.String): kotlin.Boolean {
            return FfiConverterBoolean.lift(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_slash_notes_core_fn_func_rename_item(
        FfiConverterString.lower(`rootPath`),FfiConverterString.lower(`oldRelativePath`),FfiConverterString.lower(`newName`),_status)
}
    )
    }
    

        /**
         * Restore an item from `.trash/` back to its original location.
         */
    @Throws(CoreException::class) fun `restoreFromTrash`(`rootPath`: kotlin.String, `relativePath`: kotlin.String)
        = 
    uniffiRustCallWithError(CoreException) { _status ->
    UniffiLib.INSTANCE.uniffi_slash_notes_core_fn_func_restore_from_trash(
        FfiConverterString.lower(`rootPath`),FfiConverterString.lower(`relativePath`),_status)
}
    
    
 fun `saveNote`(`dirPath`: kotlin.String, `filename`: kotlin.String, `content`: kotlin.String): kotlin.Boolean {
            return FfiConverterBoolean.lift(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_slash_notes_core_fn_func_save_note(
        FfiConverterString.lower(`dirPath`),FfiConverterString.lower(`filename`),FfiConverterString.lower(`content`),_status)
}
    )
    }
    
 fun `searchNotes`(`dirPath`: kotlin.String, `query`: kotlin.String): List<NoteHeader> {
            return FfiConverterSequenceTypeNoteHeader.lift(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_slash_notes_core_fn_func_search_notes(
        FfiConverterString.lower(`dirPath`),FfiConverterString.lower(`query`),_status)
}
    )
    }
    

    @Throws(CoreException::class) fun `syncGitRepository`(`repoPath`: kotlin.String, `token`: kotlin.String, `remoteUrl`: kotlin.String, `branch`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(CoreException) { _status ->
    UniffiLib.INSTANCE.uniffi_slash_notes_core_fn_func_sync_git_repository(
        FfiConverterString.lower(`repoPath`),FfiConverterString.lower(`token`),FfiConverterString.lower(`remoteUrl`),FfiConverterString.lower(`branch`),_status)
}
    )
    }
    


